### PR TITLE
Provisional detailed recipe view created

### PR DESCRIPTION
**Pull request by 1337adde**
I have created the detailed recipe view. It is working for now but will need som more work when we can fill it with an actual recipe from the data base. Maybe Pontus or Omer have some feedback on font style/weight/size/etc. 

I couldn't figure out the nav bar, so I created a temporary button on the start page to navigate to this view. Just for being able to see the view at all for now.

### CODE REVIEW

**Review by OmerIrfan77 — CHANGES_REQUESTED** [review]
looks good!

just two things: 
1. The page is not scrollable on my iPhone 8 simulator, i get this: 
Simulator Screenshot - iPhone 8 - 2023-11-14 at 23 24 54

2. like Xiang mentioned, try to only add the .dart files in the commits, so in your case the info.plist is imo not needed :)

**Comment by 1337adde** [comment]
I see that I did not comment the line in info.plist. The reason for it is to be able to load the pizza image when running on iPhone, so i guess it is still needed?

**Comment by OmerIrfan77** [comment]
> I see that I did not comment the line in info.plist. The reason for it is to be able to load the pizza image when running on iPhone, so i guess it is still needed?

aha ok yeah that makes sense, but in that case i guess its ok? or could also just use a url for the image for now. Until we get backend data. Either way no big deal

**Comment by 1337adde** [comment]
I think this i ready to merge now!

**Review by OmerIrfan77 — APPROVED** [review]

**Pull request merged**
